name: Build and deploy ASP.NET Core app to Azure Web App - linkupwebappdesa

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'il y a un push sur la branche main
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow depuis GitHub

jobs:
  build:
    runs-on: windows-latest  # Utilise un runner Windows pour construire ton application

    steps:
      - name: Checkout code  # Récupère le code source depuis ton dépôt GitHub
        uses: actions/checkout@v4

      - name: Set up .NET Core  # Installe la version de .NET Core spécifiée
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'  # Utilise la version .NET Core 8.x

      - name: Restore dependencies  # Restaure les dépendances NuGet
        run: dotnet restore

      - name: Build  # Compile ton application en mode Release
        run: dotnet build --configuration Release

      - name: Publish  # Publie ton application (prépare les fichiers pour le déploiement)
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload artifact for deployment job  # Sauvegarde l'artefact pour l'étape de déploiement
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish  # Le chemin vers les fichiers publiés

  deploy:
    runs-on: windows-latest  # Utilise également un runner Windows pour déployer
    needs: build  # Le job de déploiement dépend du succès du job de build

    steps:
      - name: Download artifact from build job  # Télécharge l'artefact créé pendant le build
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure  # Se connecte à Azure avec les secrets GitHub
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}  # Secret client ID Azure
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}  # Secret tenant ID Azure
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}  # Secret subscription ID Azure

      - name: Deploy to Azure Web App  # Déploie l'application sur Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'linkupwebappdesa'  # Le nom de l'App Service Azure
          slot-name: 'Production'  # Nom du slot de production
          package: './publish'  # Le dossier contenant les fichiers publiés

      - name: Output URL  # Affiche l'URL de l'application déployée
        run: echo "Deployed to ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
